{% set name = "uproot" %}
{% set version = "5.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uproot-{{ version }}.tar.gz
  sha256: b8332c76baf3f327f84972a9b4d55a72c153f324331cdb85a1b0490bd14cf1b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - hatchling >1.10.0
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - awkward >=2.4.6
    - cramjam >=2.5.0
    - python-xxhash
    - numpy
    - fsspec
    - packaging
    - typing_extensions >=4.1.0  # python < 3.11

test:
  imports:
    - uproot
    - uproot.behaviors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/uproot5
  license: BSD-3-Clause
  license_file: LICENSE
  summary: ROOT I/O in pure Python and NumPy.
  description: |
    uproot (originally Î¼proot, for "micro-Python ROOT") is a reader and a writer
    of the ROOT file format using only Python and Numpy. Unlike the standard C++
    ROOT implementation, uproot is only an I/O library, primarily intended to
    stream data into machine learning libraries in Python. Unlike PyROOT and
    root_numpy, uproot does not depend on C++ ROOT. Instead, it uses Numpy calls
    to rapidly cast data blocks in the ROOT file as Numpy arrays.
  dev_url: https://github.com/scikit-hep/uproot5
  doc_url: https://uproot.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
    - henryiii
    - agoose77
    - ioanaif
    - conda-forge/scikit-hep
